--ALTER PLUGGABLE DATABASE orclpdb OPEN;
ALTER PLUGGABLE DATABASE orcl OPEN;

-- Создание пользователя для SAU
CREATE USER SVA_RIS IDENTIFIED BY 1111;

-- Предоставление необходимых привилегий
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE DATABASE LINK TO SVA_RIS;
ALTER USER SVA_RIS QUOTA UNLIMITED ON SYSTEM;
GRANT INSERT ON RISD TO SVA_RIS;
--GRANT SELECT ON RISD TO SVA_RIS;
-- ПОДКЛЮЧИТЬСЯ К SVA_RIS И СОЗДАТЬ
CREATE DATABASE LINK DIV_TO_SVA
CONNECT TO DIV_RIS IDENTIFIED BY "1111" -- логин и пароль для студента DIV_RIS
USING 'RIS'; -- Название TNS-сервиса для подключения к серверу DIV_RIS
--DROP DATABASE LINK GDV_TO_SVA
SELECT * FROM RISV@DIV_TO_SVA;


-- от юзера
  CREATE TABLE RISD (
   id NUMBER PRIMARY KEY,
   name VARCHAR2(255) NOT NULL
);

INSERT INTO RISD (id, name) VALUES (1, 'Alice');
INSERT INTO RISD (id, name) VALUES (2, 'Bob');
INSERT INTO RISD (id, name) VALUES (3, 'Charlie');

select * from RISD
drop table RISD
-- от админа
SELECT * FROM DBA_TS_QUOTAS WHERE USERNAME = 'SVA_RIS'; 
ALTER USER SVA QUOTA UNLIMITED ON USERS;