import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(C0C62619-3BC1-4095-9B9A-84503E37DAA5),
    version(1.0),
    helpstring("IComTest interface")
]
interface IComTest : IUnknown
{
    HRESULT WhoAmI([out] LPWSTR *pwszWhoAmI);
}

[
    object,
    uuid(3BEE622B-37D6-424D-8C7C-63FADB40E3C4),  
    version(1.0),
    helpstring("ISVA interface")
]
interface ISVA : IUnknown
{
    HRESULT getThirdDigitFromEnd([in] int x, [out, retval] int* result);
}
